### ISSUE TITLE
Add pre-commit hooks

### ISSUE THREAD

**Issue by fasterinnerlooper** [sardapv/angular-material-starter-template#25]
Use husky to set up pre-commit hooks

**Comment by fasterinnerlooper** [comment]
I’ve heard that there’s a possibility that ESLint and prettier can conflict with each other. Have you made sure that they don’t keep undoing each other’s changes?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sardapv** [comment]
Yes, that's why build is green😁. You can give it a try if something is
breaking.

**Comment by sardapv** [comment]
We have already integrated prettier and eslint using local config. Prettier quick uses same config on staged files.
