### ISSUE TITLE
How to generate with latest Angular version and custom options??

### ISSUE THREAD

**Issue by TejasCMehta** [sardapv/angular-material-starter-template#39]
I want to generate with Angular 12.2 and do not want to use Angular Material at all. Can we have such custom selection during project creation like Angular CLI?

**Comment by sardapv** [comment]
Hey, This command is not using schematics right now, so unfortunately it
adds everything.

You can simply remove material related entry from package.json and 3 scss
files from material folder and relevant entry from styles.scss that's it.

**Comment by sardapv** [comment]
Also, I was in process of updating package.json to 12.2.x version. But you
can clone and update package.json for now. I will take it to latest version
soon.
