### ISSUE TITLE
Upgrade to Angular 13+1 

### ISSUE THREAD

**Issue by sardapv** [sardapv/angular-material-starter-template#40]
This needs to be upgraded to Angular 13 and dependencies.

**Comment by sardapv** [comment]
Fixes #39 partially

**Comment by sardapv** [comment]
@sjetha  if you get some free time, will you be able to checkout this? basically angular13+material13+tailwind3

**Comment by fasterinnerlooper** [comment]
A few `ng update` routines have been run and the related packages have been updated.
Some other packages can be updated as well, but these would need testing to make sure that nothing's broken.

**Comment by sardapv** [comment]
we have the build pipeline in case it fails, but I doubt so it will. Recently upgraded to 13 and tailwind 3 at workplace and everything seems fast af! specially with build cache that came with 13 XD.

**Comment by bcldvd** [comment]
Any plans to upgrade to ng13 and tailwind 3? :)

**Comment by sardapv** [comment]
@bcldvd was away for quite a while due to ofc. migrating this project to latest angular this weekend.

**Comment by sardapv** [comment]
New version released 🎉
